### ISSUE TITLE
Join forces?

### ISSUE THREAD

**Issue by thoas** [pixiv/go-thumber#5]
Hi,

I'm developing [picfit](https://github.com/thoas/picfit) which is exactly the same project as yours.

Are you interested to join force with me?

I want an credible alternative to [thumbor](https://github.com/thumbor/thumbor)

**Comment by edvakf** [comment]
Hi. I'm not a maintainer of go-thumber, but work for pixiv.

It seems the purpose for picfit differs from that of go-thumber slightly. go-thumber is meant to be used behind a reverse proxy and only handles jpeg images that are already pre-converted (for example using ImageMagick). Nonetheless, the performance gain is quite huge. We think go-thumber's interface should stay simple.

In our future (probably complete different) use cases, we might consider using picfit rather than making our own.

**Comment by thoas** [comment]
Thank you for your quick reply.

If I look to your code, you are doing the same job as picfit (which is also meant to be used behind a reverse proxy), [downloading](https://github.com/pixiv/go-thumber/blob/master/thumberd/thumberd.go#L153), [resizing on the fly](https://github.com/pixiv/go-thumber/blob/master/thumberd/thumberd.go#L167) using parameters in the URL which is exactly what I'm doing but instead of supporting just the http provider, I'm also supporting fs, s3, etc.

[Here](https://github.com/thoas/picfit/blob/master/application/application.go#L79) is the main implementation :)

**Comment by edvakf** [comment]
I see.

We have plans to split image processing part to https://github.com/pixiv/go-libjpeg and go-swscale (yet to come) that support go.image interfaces. They might be useful if you need speed. We are open to contributions too.

Let me close this issue because it's not really an issue. Thanks.
